// Loads the real, shipped playground script — the largest inline <script> in
// promo/playground/index.html, generated by build_promo.py's build_playground_script() — into a
// Node vm with a thin mock DOM, so tests exercise the actual generated code rather than a
// reimplementation of it.
//
// Why a mock DOM rather than a browser: the engine bundle (promo/vendor/polytypo.browser.js) needs
// a real DOM for its html mode and will not load under Node, and CI has no browser. That bounds
// what tests built on this can claim — they drive the CONTROLS and read what the script puts in
// the input and the call blocks, all of which is pure string building over the form's state. To
// check what the engine then DOES with a sample, call `transform` from the `polytypo` package
// directly on the input this harness produced; `polytypo` is a devDependency here for exactly
// that kind of measurement.
//
// The mock is deliberately thin: the script touches only getElementById, createElement/appendChild,
// document.head, document.readyState, and optionally ResizeObserver/IntersectionObserver (both
// feature-detected with `typeof === "function"`, so leaving them undefined is a supported path).
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import vm from "node:vm";

export const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");

/** One mock element. Only the properties the playground script actually reads or writes. */
export class El {
  value = "";
  textContent = "";
  innerHTML = "";
  hidden = false;
  offsetHeight = 100;
  scrollHeight = 100;
  style: Record<string, string> = {};
  options: unknown[] = [];
  classList = { add() {}, remove() {} };
  listeners: Record<string, ((...args: unknown[]) => void)[]> = {};
  addEventListener(type: string, fn: (...args: unknown[]) => void) {
    (this.listeners[type] ??= []).push(fn);
  }
  appendChild(child: unknown) {
    this.options.push(child);
  }
  /** Fires every handler registered for `type`, the way a real event would. */
  fire(type: string) {
    for (const fn of this.listeners[type] ?? []) fn({ type });
  }
}

export interface Harness {
  el: (id: string) => El;
  /** Sets the form to a state and lets the script's 120 ms debounce elapse. */
  set: (state: {
    input?: string;
    mode?: string;
    dialect?: string;
    keys?: string;
    locale?: string;
  }) => Promise<void>;
  /** The visible text of each language's call block, entities decoded. */
  calls: () => Record<string, string>;
  /** Whatever the script currently has in the input textarea. */
  input: () => string;
  /** The comma-separated Keys field, as the script would read it. */
  keysField: () => string;
}

/** The default `value` the shipped markup gives a control, which the browser applies and this
 * mock does not — read straight out of playground.partial.html so a test can assert on it. */
export function markupDefault(id: string): string {
  const markup = readFileSync(
    path.join(ROOT, "brand", "tools", "promo", "playground.partial.html"),
    "utf8",
  );
  const tag = new RegExp(`<input[^>]*\\bid="${id}"[\\s\\S]*?/>`).exec(markup);
  if (!tag) throw new Error(`no <input id="${id}"> in playground.partial.html`);
  return /\bvalue="([^"]*)"/.exec(tag[0])?.[1] ?? "";
}

/** Extracts the playground's inline script from the generated page. */
export function playgroundSource(): string {
  const html = readFileSync(path.join(ROOT, "promo", "playground", "index.html"), "utf8");
  // The playground script is the largest inline script on the page; `src`-bearing tags are skipped.
  const inline = [...html.matchAll(/<script(?![^>]*\ssrc)[^>]*>([\s\S]*?)<\/script>/g)].map(
    (m) => m[1] ?? "",
  );
  const source: string = inline.reduce((a, b) => (b.length > a.length ? b : a), "");
  if (source.length < 1000) throw new Error("no inline playground script in the generated page");
  return source;
}

/**
 * Boots the playground script against a mock DOM.
 *
 * `applyMarkupDefaults` mirrors what a browser does with the `value` attributes in
 * playground.partial.html before any script runs — without it the Keys field starts empty, which
 * is a state the real page never has.
 */
export function loadPlayground(applyMarkupDefaults = true): Harness {
  const source = playgroundSource();

  const els = new Map<string, El>();
  const el = (id: string) => {
    let found = els.get(id);
    if (!found) els.set(id, (found = new El()));
    return found;
  };

  if (applyMarkupDefaults) el("pg-keys").value = markupDefault("pg-keys");

  const document = {
    getElementById: (id: string) => el(id),
    createElement: () => new El(),
    querySelectorAll: () => [] as unknown[],
    addEventListener: () => {},
    head: new El(),
    body: new El(),
    readyState: "complete",
    documentElement: new El(),
  };
  const sandbox: Record<string, unknown> = {
    document,
    setTimeout,
    clearTimeout,
    console,
    navigator: { clipboard: { writeText: async () => {} } },
  };
  sandbox.window = sandbox;
  vm.createContext(sandbox);

  // site.js supplies highlightLines/bootTabs/track, which the playground script reads off
  // window.Polytypo — the same dependency direction the page has.
  vm.runInContext(readFileSync(path.join(ROOT, "brand/tools/promo/site.js"), "utf8"), sandbox, {
    filename: "site.js",
  });
  vm.runInContext(source, sandbox, { filename: "playground.inline.js" });

  const set: Harness["set"] = async (state) => {
    // Order matters: the control whose change fires last is the one whose handler re-samples, and
    // a real visitor also changes one control at a time.
    if (state.input !== undefined) {
      el("pg-input").value = state.input;
      el("pg-input").fire("input");
    }
    if (state.keys !== undefined) {
      el("pg-keys").value = state.keys;
      el("pg-keys").fire("input");
    }
    if (state.locale !== undefined) {
      el("pg-locale").value = state.locale;
      el("pg-locale").fire("change");
    }
    if (state.mode !== undefined) {
      el("pg-mode").value = state.mode;
      el("pg-mode").fire("change");
    }
    if (state.dialect !== undefined) {
      el("pg-dialect").value = state.dialect;
      el("pg-dialect").fire("change");
    }
    // The script debounces render() by 120 ms.
    await new Promise((r) => setTimeout(r, 200));
  };

  // What a reader sees: highlightLines wraps each line in <span class="ln"> and escapes the
  // markup-significant characters, so assertions are written against the visible text rather than
  // against that wrapping — the wrapping is pinned by code-panels.test.ts, which owns it.
  const visible = (html: string) =>
    html
      .replace(/<[^>]+>/g, "")
      .replace(/&lt;/g, "<")
      .replace(/&gt;/g, ">")
      .replace(/&quot;/g, '"')
      .replace(/&#39;/g, "'")
      .replace(/&amp;/g, "&");

  return {
    el,
    set,
    input: () => el("pg-input").value,
    keysField: () => el("pg-keys").value,
    calls: () => ({
      js: visible(el("call-code-js").innerHTML),
      py: visible(el("call-code-py").innerHTML),
      go: visible(el("call-code-go").innerHTML),
      rb: visible(el("call-code-rb").innerHTML),
      php: visible(el("call-code-php").innerHTML),
    }),
  };
}
