// Exercises the real, shipped playground script — the largest inline <script> in
// promo/playground/index.html, generated by build_promo.py's build_playground_script() — in a Node
// vm with a mock DOM. Nothing else in this suite executes that script at all: the other promo
// tests read the generated HTML as text, so every branch in the playground's own logic was
// previously unverified by CI.
//
// Why a mock DOM rather than a browser: the engine bundle (promo/vendor/polytypo.browser.js) needs
// a real DOM for its html mode and will not load under Node, and CI has no browser. That is a real
// limit, and it bounds what this file claims — it drives the CONTROLS and asserts the CALL BLOCKS,
// which are pure string building over the form's state. It never runs `transform`, so it proves
// what the page *says* it will call, not what the engine then returns. The engine's own behaviour
// is pinned by the canonical fixtures in every runtime repo, which is the right place for it.
//
// The mock is deliberately thin: the script touches only getElementById, createElement/appendChild,
// document.head, document.readyState, and optionally ResizeObserver/IntersectionObserver (both
// feature-detected with `typeof === "function"`, so leaving them undefined is a supported path).
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import vm from "node:vm";
import { describe, expect, it } from "vitest";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");

/** One mock element. Only the properties the playground script actually reads or writes. */
class El {
  value = "";
  textContent = "";
  innerHTML = "";
  hidden = false;
  offsetHeight = 100;
  scrollHeight = 100;
  style: Record<string, string> = {};
  options: unknown[] = [];
  classList = { add() {}, remove() {} };
  listeners: Record<string, ((...args: unknown[]) => void)[]> = {};
  addEventListener(type: string, fn: (...args: unknown[]) => void) {
    (this.listeners[type] ??= []).push(fn);
  }
  appendChild(child: unknown) {
    this.options.push(child);
  }
  /** Fires every handler registered for `type`, the way a real event would. */
  fire(type: string) {
    for (const fn of this.listeners[type] ?? []) fn({ type });
  }
}

interface Harness {
  el: (id: string) => El;
  /** Sets the form to a state and lets the script's 120 ms debounce elapse. */
  set: (state: { input?: string; mode?: string; keys?: string; locale?: string }) => Promise<void>;
  calls: () => Record<string, string>;
}

function loadPlayground(): Harness {
  const html = readFileSync(path.join(ROOT, "promo", "playground", "index.html"), "utf8");
  // The playground script is the largest inline script on the page; `src`-bearing tags are skipped.
  const inline = [...html.matchAll(/<script(?![^>]*\ssrc)[^>]*>([\s\S]*?)<\/script>/g)].map(
    (m) => m[1] ?? "",
  );
  const source: string = inline.reduce((a, b) => (b.length > a.length ? b : a), "");
  expect(source.length, "no inline playground script found in the generated page").toBeGreaterThan(
    1000,
  );

  const els = new Map<string, El>();
  const el = (id: string) => {
    let found = els.get(id);
    if (!found) els.set(id, (found = new El()));
    return found;
  };

  const document = {
    getElementById: (id: string) => el(id),
    createElement: () => new El(),
    querySelectorAll: () => [] as unknown[],
    addEventListener: () => {},
    head: new El(),
    body: new El(),
    readyState: "complete",
    documentElement: new El(),
  };
  const sandbox: Record<string, unknown> = {
    document,
    setTimeout,
    clearTimeout,
    console,
    navigator: { clipboard: { writeText: async () => {} } },
  };
  sandbox.window = sandbox;
  vm.createContext(sandbox);

  // site.js supplies highlightLines/bootTabs/track, which the playground script reads off
  // window.Polytypo — the same dependency direction the page has.
  vm.runInContext(readFileSync(path.join(ROOT, "brand/tools/promo/site.js"), "utf8"), sandbox, {
    filename: "site.js",
  });
  vm.runInContext(source, sandbox, { filename: "playground.inline.js" });

  const set: Harness["set"] = async (state) => {
    if (state.locale !== undefined) el("pg-locale").value = state.locale;
    if (state.input !== undefined) el("pg-input").value = state.input;
    if (state.keys !== undefined) el("pg-keys").value = state.keys;
    if (state.mode !== undefined) {
      el("pg-mode").value = state.mode;
      el("pg-mode").fire("change");
    } else {
      el("pg-input").fire("input");
    }
    // The script debounces render() by 120 ms.
    await new Promise((r) => setTimeout(r, 200));
  };

  // What a reader sees: highlightLines wraps each line in <span class="ln"> and escapes the
  // markup-significant characters, so assertions are written against the visible text rather than
  // against that wrapping — the wrapping is pinned by code-panels.test.ts, which owns it.
  const visible = (html: string) =>
    html
      .replace(/<[^>]+>/g, "")
      .replace(/&lt;/g, "<")
      .replace(/&gt;/g, ">")
      .replace(/&quot;/g, '"')
      .replace(/&#39;/g, "'")
      .replace(/&amp;/g, "&");

  const calls = () => ({
    js: visible(el("call-code-js").innerHTML),
    py: visible(el("call-code-py").innerHTML),
    go: visible(el("call-code-go").innerHTML),
    rb: visible(el("call-code-rb").innerHTML),
    php: visible(el("call-code-php").innerHTML),
  });

  return { el, set, calls };
}

const YAML_INPUT = 'description: He said "hi" to us\nrun: echo "hi"\n';

describe("playground yaml mode — the controls", () => {
  it("offers yaml as a fourth mode, with the Keys field hidden until it is chosen", async () => {
    const pg = loadPlayground();
    // render() runs once at startup and sets both wrappers from the initial mode ("text").
    expect(pg.el("pg-keys-wrap").hidden).toBe(true);
    expect(pg.el("pg-dialect-wrap").hidden).toBe(true);

    await pg.set({ locale: "en-US", input: YAML_INPUT, mode: "yaml" });
    expect(pg.el("pg-keys-wrap").hidden).toBe(false);
    expect(pg.el("pg-dialect-wrap").hidden, "dialect is markdown-only").toBe(true);
  });

  it("hides the Keys field again when the mode moves away from yaml", async () => {
    const pg = loadPlayground();
    await pg.set({ locale: "en-US", input: YAML_INPUT, mode: "yaml" });
    expect(pg.el("pg-keys-wrap").hidden).toBe(false);
    await pg.set({ mode: "markdown" });
    expect(pg.el("pg-keys-wrap").hidden).toBe(true);
    expect(pg.el("pg-dialect-wrap").hidden).toBe(false);
  });
});

describe("playground yaml mode — the call block it shows", () => {
  it("names keys in all five languages, each in that language's own syntax", async () => {
    const pg = loadPlayground();
    await pg.set({
      locale: "en-US",
      input: YAML_INPUT,
      mode: "yaml",
      keys: "description, title",
    });
    const c = pg.calls();
    expect(c.js).toContain('keys: ["description", "title"]');
    expect(c.py).toContain('keys=["description", "title"]');
    expect(c.go).toContain('[]string{"description", "title"}');
    expect(c.rb).toContain('keys: ["description", "title"]');
    expect(c.php).toContain("'keys' => ['description', 'title']");
  });

  it("shows keys only in yaml mode, and dialect only in markdown", async () => {
    const pg = loadPlayground();
    await pg.set({ locale: "en-US", input: "plain text", mode: "text" });
    for (const [lang, code] of Object.entries(pg.calls())) {
      expect(code, `${lang} names keys in text mode`).not.toMatch(/\bkeys\b/);
      expect(code, `${lang} names dialect in text mode`).not.toMatch(/\bdialect\b/i);
    }

    await pg.set({ mode: "markdown" });
    for (const [lang, code] of Object.entries(pg.calls())) {
      expect(code, `${lang} names keys in markdown mode`).not.toMatch(/\bkeys\b/);
      expect(code, `${lang} omits dialect in markdown mode`).toMatch(/dialect/i);
    }
  });

  it("drops blank entries rather than passing an empty key that matches nothing", async () => {
    // "description, title," parses to two keys, not three: an empty string is a legal key that
    // matches no line, so leaving it in would narrow the result silently.
    const pg = loadPlayground();
    await pg.set({
      locale: "en-US",
      input: YAML_INPUT,
      mode: "yaml",
      keys: "description, title,",
    });
    expect(pg.calls().js).toContain('keys: ["description", "title"]');

    await pg.set({ keys: " , , " });
    await pg.set({ input: YAML_INPUT + " " }); // re-render; keys has no change event of its own here
    expect(pg.calls().js, "an all-separator field is an empty list").toContain("keys: []");
  });

  it("escapes a typed key rather than injecting it into the snippet", async () => {
    // Keys are the one free-text control in the bar. A quote or backslash typed there must come
    // back as a string literal in every language, never as syntax.
    const pg = loadPlayground();
    await pg.set({
      locale: "en-US",
      input: YAML_INPUT,
      mode: "yaml",
      keys: 'a"b, c\\d',
    });
    const c = pg.calls();
    // JSON.stringify escapes both for the JS/Python/Go/Ruby literals.
    expect(c.js).toContain('"a\\"b"');
    expect(c.js).toContain('"c\\\\d"');
    // PHP single-quoted literals escape the backslash; a double quote needs no escaping there.
    expect(c.php).toContain("'a\"b'");
    expect(c.php).toContain("'c\\\\d'");
  });
});
